import turtle as t

t.penup()
t.color("#CE1126")
t.goto(-120, 75)
t.pendown()
t.begin_fill()
for i in range(2):
    t.forward(240)
    t.right(90)
    t.forward(30)
    t.right(90)
t.end_fill()
t.penup()

t.color("#FCD116")
t.goto(-120, 45)
t.pendown()
t.begin_fill()
for i in range(2):
    t.forward(240)
    t.right(90)
    t.forward(30)
    t.right(90)
t.end_fill()
t.penup()

t.color("#002B7F")
t.goto(-120, 15)
t.pendown()
t.begin_fill()
for i in range(2):
    t.forward(240)
    t.right(90)
    t.forward(30)
    t.right(90)
t.end_fill()
t.penup()

t.color("#FFFFFF")
t.goto(-120, -15)
t.pendown()
t.begin_fill()
for i in range(2):
    t.forward(240)
    t.right(90)
    t.forward(30)
    t.right(90)
t.end_fill()
t.penup()

t.color("#000000")
t.goto(-120, -45)
t.pendown()
t.begin_fill()
for i in range(2):
    t.forward(240)
    t.right(90)
    t.forward(30)
    t.right(90)
t.end_fill()
t.penup()
t.hideturtle()
t.done()